<?
require($_SERVER["DOCUMENT_ROOT"]."/bitrix/header.php");
$APPLICATION->SetTitle("Сотрудники");
?>

<div class="row">
	<div class="col-lg-12">
		<h1 class="page-header">
			<?$APPLICATION->ShowTitle()?>
		</h1>
		<?$APPLICATION->IncludeComponent(
			"bitrix:breadcrumb", 
			"omi_breadcrumb", 
			array(
				"COMPONENT_TEMPLATE" => "omi_breadcrumb",
				"PATH" => "",
				"SITE_ID" => "s1",
				"START_FROM" => "0"
			),
			false
		);?>
	</div>
</div>

<?$APPLICATION->IncludeComponent(
	"bitrix:news", 
	"omi_people", 
	array(
		"ADD_ELEMENT_CHAIN" => "N",
		"ADD_SECTIONS_CHAIN" => "N",
		"AJAX_MODE" => "N",
		"AJAX_OPTION_ADDITIONAL" => "",
		"AJAX_OPTION_HISTORY" => "N",
		"AJAX_OPTION_JUMP" => "N",
		"AJAX_OPTION_STYLE" => "Y",
		"BROWSER_TITLE" => "FULL_NAME",
		"CACHE_FILTER" => "N",
		"CACHE_GROUPS" => "Y",
		"CACHE_TIME" => "36000000",
		"CACHE_TYPE" => "A",
		"CHECK_DATES" => "Y",
		"COMPONENT_TEMPLATE" => "omi_people",
		"DETAIL_ACTIVE_DATE_FORMAT" => "d.m.Y",
		"DETAIL_DISPLAY_BOTTOM_PAGER" => "Y",
		"DETAIL_DISPLAY_TOP_PAGER" => "N",
		"DETAIL_FIELD_CODE" => array(
			0 => "",
			1 => "",
		),
		"DETAIL_PAGER_SHOW_ALL" => "Y",
		"DETAIL_PAGER_TEMPLATE" => "",
		"DETAIL_PAGER_TITLE" => "Страница",
		"DETAIL_PROPERTY_CODE" => array(
			0 => "FULL_NAME",
			1 => "FULL_NAME_EN",
			2 => "EMAIL",
			3 => "SURNAME",
			4 => "NAME",
			5 => "PATRONIM",
			6 => "DESCRIPTION",
			7 => "SURNAME_EN",
			8 => "NAME_EN",
			9 => "PATRONIM_EN",
			10 => "DESCRIPTION_EN",
			11 => "RANK",
			12 => "DEGREE",
			13 => "DATE_OF_BIRTH",
			14 => "VAK_SPEC_EN",
			15 => "VAK_SPEC",
			16 => "KEYWORDS",
			17 => "KEYWORDS_EN",
			18 => "UDK",
			19 => "MSC",
			20 => "NIR_SUBJECT",
			21 => "NIR_SUBJECT_EN",
			22 => "",
		),
		"DETAIL_SET_CANONICAL_URL" => "N",
		"DISPLAY_BOTTOM_PAGER" => "Y",
		"DISPLAY_DATE" => "Y",
		"DISPLAY_NAME" => "N",
		"DISPLAY_PICTURE" => "Y",
		"DISPLAY_PREVIEW_TEXT" => "Y",
		"DISPLAY_TOP_PAGER" => "N",
		"HIDE_LINK_WHEN_NO_DETAIL" => "N",
		"IBLOCK_ID" => "5",
		"IBLOCK_TYPE" => "news",
		"INCLUDE_IBLOCK_INTO_CHAIN" => "N",
		"LIST_ACTIVE_DATE_FORMAT" => "d.m.Y",
		"LIST_FIELD_CODE" => array(
			0 => "",
			1 => "",
		),
		"LIST_PROPERTY_CODE" => array(
			0 => "FULL_NAME",
			1 => "FULL_NAME_EN",
			2 => "EMAIL",
			3 => "SURNAME",
			4 => "NAME",
			5 => "PATRONIM",
			6 => "DESCRIPTION",
			7 => "SURNAME_EN",
			8 => "NAME_EN",
			9 => "PATRONIM_EN",
			10 => "DESCRIPTION_EN",
			11 => "RANK",
			12 => "DEGREE",
			13 => "DATE_OF_BIRTH",
			14 => "VAK_SPEC_EN",
			15 => "VAK_SPEC",
			16 => "KEYWORDS",
			17 => "KEYWORDS_EN",
			18 => "UDK",
			19 => "MSC",
			20 => "NIR_SUBJECT",
			21 => "NIR_SUBJECT_EN",
			22 => "",
		),
		"MESSAGE_404" => "",
		"META_DESCRIPTION" => "-",
		"META_KEYWORDS" => "-",
		"NEWS_COUNT" => "20",
		"PAGER_BASE_LINK_ENABLE" => "N",
		"PAGER_DESC_NUMBERING" => "N",
		"PAGER_DESC_NUMBERING_CACHE_TIME" => "36000",
		"PAGER_SHOW_ALL" => "N",
		"PAGER_SHOW_ALWAYS" => "N",
		"PAGER_TEMPLATE" => ".default",
		"PAGER_TITLE" => "Новости",
		"PREVIEW_TRUNCATE_LEN" => "",
		"SEF_FOLDER" => "/scientist/",
		"SEF_MODE" => "Y",
		"SET_LAST_MODIFIED" => "N",
		"SET_STATUS_404" => "N",
		"SET_TITLE" => "Y",
		"SHOW_404" => "N",
		"SORT_BY1" => "ACTIVE_FROM",
		"SORT_BY2" => "SORT",
		"SORT_ORDER1" => "DESC",
		"SORT_ORDER2" => "ASC",
		"USE_CATEGORIES" => "N",
		"USE_FILTER" => "N",
		"USE_PERMISSIONS" => "N",
		"USE_RATING" => "N",
		"USE_RSS" => "N",
		"USE_SEARCH" => "N",
		"USE_SHARE" => "N",
		"SEF_URL_TEMPLATES" => array(
			"news" => "",
			"section" => "",
			"detail" => "#ELEMENT_CODE#/",
		)
	),
	false
);?>

<?require($_SERVER["DOCUMENT_ROOT"]."/bitrix/footer.php");?>